expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
html_errors = Off
error_reporting = 0

open_basedir = /var/www/html:/tmp
sys_temp_dir = /tmp
upload_tmp_dir = /tmp
session.save_path = /tmp

allow_url_fopen = Off
allow_url_include = Off
file_uploads = Off
enable_dl = Off
ffi.enable = false
phar.readonly = On
mail.add_x_header = Off

memory_limit = 256M
max_execution_time = 30
max_input_time = 30
max_input_vars = 100000
max_input_nesting_level = 512
post_max_size = 2M
upload_max_filesize = 1M
max_file_uploads = 0
variables_order = "GPCS"
request_order = "GP"

disable_functions = spl_autoload_register,spl_autoload_unregister,apache_child_terminate,apache_get_modules,apache_get_version,apache_getenv,apache_lookup_uri,apache_note,apache_request_headers,apache_response_headers,apache_setenv,chgrp,chmod,chown,chroot,copy,curl_exec,curl_multi_exec,dl,error_log,exec,file,file_get_contents,file_put_contents,fopen,fsockopen,getallheaders,glob,gzfile,gzopen,gzpassthru,highlight_file,imap_mail,ini_alter,ini_restore,ini_set,link,mail,mb_send_mail,mkdir,openlog,opcache_compile_file,opcache_get_configuration,opcache_get_status,opcache_invalidate,opcache_is_script_cached,opcache_reset,passthru,pclose,pcntl_alarm,pcntl_async_signals,pcntl_exec,pcntl_fork,pcntl_get_last_error,pcntl_getpriority,pcntl_setpriority,pcntl_signal,pcntl_signal_dispatch,pcntl_sigprocmask,pcntl_sigtimedwait,pcntl_sigwaitinfo,pcntl_strerror,pcntl_wait,pcntl_waitpid,pcntl_wexitstatus,pcntl_wifcontinued,pcntl_wifexited,pcntl_wifsignaled,pcntl_wifstopped,pcntl_wstopsig,pcntl_wtermsig,pfsockopen,phpinfo,popen,proc_close,proc_get_status,proc_nice,proc_open,proc_terminate,putenv,readfile,readgzfile,readlink,rename,request_parse_body,rmdir,scandir,shell_exec,show_source,stream_filter_register,stream_register_wrapper,stream_resolve_include_path,stream_socket_accept,stream_socket_client,stream_socket_enable_crypto,stream_socket_get_name,stream_socket_pair,stream_socket_recvfrom,stream_socket_sendto,stream_socket_server,stream_socket_shutdown,stream_wrapper_register,stream_wrapper_restore,stream_wrapper_unregister,symlink,syslog,system,unlink,virtual
disable_classes = DateInterval

opcache.enable = 0
opcache.enable_cli = 0
opcache.validate_timestamps = 0
opcache.jit = 0
