#!/usr/bin/env sage
"""exp.sage — Cuneiform solution (intersection attack + Plucker seal)."""


# This file was *autogenerated* from the file /Users/komiko/uov/vela_array_v1/Cuneiform/exp/exp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_36 = Integer(36); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_256 = Integer(256); _sage_const_7 = Integer(7)
import sys, ast, hashlib, time
from itertools import combinations

SEAL_DOMAIN = b"sctf-ur-v7|seal|"
SEAL_STREAM = b"seal|"

def parse_output(path):
    d = {"C": []}
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line: continue
        k, _, v = line.partition("="); k, v = k.strip(), v.strip()
        if k in ("p", "w", "N", "M"): d[k] = int(v)
        elif k == "modulus": d["modulus"] = ast.literal_eval(v)
        elif k == "profile": d["profile"] = ast.literal_eval(v)
        elif k == "seal_nonce": d["seal_nonce"] = bytes.fromhex(v)
        elif k == "vault": d["vault"] = bytes.fromhex(v)
        elif k and k[_sage_const_0 ] == "C" and k[_sage_const_1 :].isdigit(): d["C"].append((int(k[_sage_const_1 :]), v))
    d["C"] = [b for _, b in sorted(d["C"])]
    return d

def build_field(p, w, coeffs):
    Fp = GF(p); Rx = PolynomialRing(Fp, 'X'); X = Rx.gen()
    g = sum(Fp(coeffs[i]) * X**i for i in range(len(coeffs)))
    return GF(p**w, name='z', modulus=g)

def int_to_K(K, p, w, code):
    d = []
    for _ in range(w):
        d.append(code % p)
        code //= p
    return K(d)

def K_to_int(K, p, w, elt):
    c = elt.polynomial().list(); c += [_sage_const_0 ]*(w - len(c))
    return sum(int(c[i])*(p**i) for i in range(w))

def unpack_coupling(K, p, w, blob, N):
    inv2 = K(_sage_const_2 )**(-_sage_const_1 ); order = [(i, j) for i in range(N) for j in range(i, N)]
    val = Integer(int(blob, _sage_const_36 )); C = matrix(K, N, N)
    for (i, j) in order:
        val, c = val.quo_rem(p**w)
        if c == _sage_const_0 : continue
        elt = int_to_K(K, p, w, int(c))
        if i == j: C[i, i] = elt
        else: v = elt * inv2; C[i, j] = v; C[j, i] = v
    return C

def rref_first_pivot(M):
    R = M.__copy__(); rows, cols = R.nrows(), R.ncols(); pivots = []; r = _sage_const_0 
    for c in range(cols):
        if r >= rows: break
        piv = None
        for i in range(r, rows):
            if R[i, c] != _sage_const_0 : piv = i; break
        if piv is None: continue
        if piv != r: R.swap_rows(r, piv)
        R[r] = R[r] * (R[r, c]**(-_sage_const_1 ))
        for i in range(rows):
            if i != r and R[i, c] != _sage_const_0 : R[i] = R[i] - R[i, c] * R[r]
        pivots.append(c); r += _sage_const_1 
    return R, pivots

def quad(C, x):
    xv = vector(C.base_ring(), x) if not hasattr(x, 'parent') else x; return xv * C * xv

def bilin(C, x, y):
    xv = vector(C.base_ring(), x) if not hasattr(x, 'parent') else x
    yv = vector(C.base_ring(), y) if not hasattr(y, 'parent') else y; return xv * C * yv

def main():
    d = parse_output(sys.argv[_sage_const_1 ] if len(sys.argv) > _sage_const_1  else "output.txt")
    p, w, N, M = d["p"], d["w"], d["N"], d["M"]
    print(f"[*] GF({p}^{w}), N={N}, M={M}")

    K = build_field(p, w, d["modulus"])
    couplings = [unpack_coupling(K, p, w, b, N) for b in d["C"]]
    profile_K = [int_to_K(K, p, w, int(t) % (p**w)) for t in d["profile"]]
    polars = [C + C.transpose() for C in couplings]

    i, j = next((a,b) for a in range(M) for b in range(a+_sage_const_1 ,M)
                if polars[a].is_invertible() and polars[b].is_invertible())
    Mi_inv, Mj_inv = polars[i].inverse(), polars[j].inverse()
    NV = N - _sage_const_3 
    trial = [K(_sage_const_0 ), K(_sage_const_1 ), K(_sage_const_2 ), K.gen(), K.gen()+_sage_const_1 , K.gen()+_sage_const_2 , _sage_const_2 *K.gen(), _sage_const_2 *K.gen()+_sage_const_1 , _sage_const_2 *K.gen()+_sage_const_2 ]
    trial = list(dict.fromkeys(trial))
    print(f"[*] {NV} variables, {len(trial)} trials")

    hits, t0 = [], time.time()
    for a in trial:
        if len(hits) >= _sage_const_2 : break
        for b in trial:
            if len(hits) >= _sage_const_2 : break
            for c in trial:
                if a==_sage_const_0  and b==_sage_const_0  and c==_sage_const_0 : continue
                if len(hits) >= _sage_const_2 : break
                R = PolynomialRing(K, [f"x{t}" for t in range(NV)], order="degrevlex")
                xs = list(R.gens()); x = vector(R, [a,b,c]+xs); yi = Mi_inv*x; yj = Mj_inv*x
                eqs = [quad(Ck,yi) for Ck in couplings] + [quad(Ck,yj) for Ck in couplings] + [bilin(Ck,yi,yj) for Ck in couplings]
                I = R.ideal(eqs)
                if I.dimension() != _sage_const_0 : continue
                Rlex = PolynomialRing(K, [f"x{t}" for t in range(NV)], order="lex")
                xs_lex = list(Rlex.gens()); x_lex = vector(Rlex, [a,b,c]+xs_lex)
                yi_lex = Mi_inv*x_lex; yj_lex = Mj_inv*x_lex
                eqs_lex = [quad(Ck,yi_lex) for Ck in couplings] + [quad(Ck,yj_lex) for Ck in couplings] + [bilin(Ck,yi_lex,yj_lex) for Ck in couplings]
                Ilex = Rlex.ideal(eqs_lex)
                for sol in Ilex.variety():
                    oi = Mi_inv * vector(K, [a,b,c]+[sol[Rlex.gen(t)] for t in range(NV)])
                    oj = Mj_inv * vector(K, [a,b,c]+[sol[Rlex.gen(t)] for t in range(NV)])
                    if oi==_sage_const_0  or oj==_sage_const_0 : continue
                    if not all(quad(Ck,oi)==_sage_const_0  and quad(Ck,oj)==_sage_const_0  and bilin(Ck,oi,oj)==_sage_const_0  for Ck in couplings): continue
                    for v in (oi,oj):
                        if not hits or matrix(K, hits+[v]).rank() > matrix(K, hits).rank():
                            hits.append(v)
                            print(f"  vector #{len(hits)} ({time.time()-t0:.1f}s)")
    print(f"[+] {len(hits)} vectors ({time.time()-t0:.1f}s)")
    assert len(hits) >= _sage_const_2 

    rows = [list((C+C.transpose())*vector(K,v)) for v in hits for C in couplings]
    ker = matrix(K, rows).right_kernel()
    Kmat = ker.basis_matrix(); basis = [Kmat.row(r) for r in range(Kmat.nrows())]
    blind = [b for b in basis if all(quad(C,b)==_sage_const_0  for C in couplings)]
    family = None
    for subset in combinations(blind, M):
        Fam = matrix(K, list(subset))
        if Fam.rank() < M: continue
        if all((Fam*(C+C.transpose())*Fam.transpose()).is_zero() for C in couplings):
            family = [list(Fam.row(r)) for r in range(M)]; break
    assert family is not None
    print(f"[+] W recovered (dim={M})")

    Fmat = matrix(K, family); Rref, pivots = rref_first_pivot(Fmat)
    Q = Rref[:len(pivots),:]; frees = [c for c in range(N) if c not in set(pivots)]
    def sw(seed, count):
        raw = hashlib.shake_256(seed).digest(count*_sage_const_8 )
        return [int_to_K(K,p,w,int.from_bytes(raw[_sage_const_8 *i:_sage_const_8 *i+_sage_const_8 ],"big")%(p**w)) for i in range(count)]
    for ctr in range(_sage_const_256 ):
        u = sw(d["seal_nonce"]+ctr.to_bytes(_sage_const_2 ,"big"), len(frees))
        wv = [K(_sage_const_0 )]*N
        for jj, fc in enumerate(frees): wv[fc] = u[jj]
        wrow = vector(K, wv); L, rhs = [], []
        for k in range(M):
            rhs.append(profile_K[k] - quad(couplings[k], wv))
            wB = wrow * polars[k]; L.append([wB*Q.row(i) for i in range(Q.nrows())])
        Lm = matrix(K, L)
        if Lm.rank() < Q.nrows(): continue
        try: cc = Lm.solve_right(vector(K, rhs))
        except ValueError: continue
        s = wrow + cc*Q
        if all(quad(couplings[k], list(s)) == profile_K[k] for k in range(M)):
            pattern, cal_ctr = list(s), ctr; break
    print(f"[+] calibration ctr={cal_ctr}")

    Fam2 = matrix(K, family); plucker = []
    for cols_tuple in combinations(range(N), M):
        plucker.append(Fam2.matrix_from_columns(list(cols_tuple)).det())
    fn = next(i for i,v in enumerate(plucker) if v!=_sage_const_0 )
    plucker_norm = [v * plucker[fn]**(-_sage_const_1 ) for v in plucker]
    print(f"[+] Plucker: {len(plucker)} coords")

    width = ((p**w).bit_length()+_sage_const_7 )//_sage_const_8 
    wb = b"".join(int(K_to_int(K,p,w,x)).to_bytes(width,"big") for x in pattern)
    pb = b"".join(int(K_to_int(K,p,w,x)).to_bytes(width,"big") for x in profile_K)
    plb = b"".join(int(K_to_int(K,p,w,x)).to_bytes(width,"big") for x in plucker_norm)
    seal = hashlib.sha256(SEAL_DOMAIN + wb + b"|" + pb + b"|" + plb + b"|" + f"{p}^{w}".encode()).digest()
    ks = hashlib.shake_256(SEAL_STREAM + seal).digest(len(d["vault"]))
    payload = bytes([a.__xor__(b) for a,b in zip(d["vault"], ks)])
    try: text = payload.decode()
    except UnicodeDecodeError: text = repr(payload)
    print(f"[+] FLAG: {text}")

if __name__ == "__main__": main()

